package org.tavall.couriers.web.view.css.page.popup;

public final class CameraPopupCss {

    public static final String CAMERA_POPUP_CSS = String.join("\n",
            "/* Camera popup */",
            ".scan-overlay {",
            "    position: fixed;",
            "    inset: 0;",
            "    background: rgba(8, 12, 20, 0.78);",
            "    display: flex;",
            "    align-items: center;",
            "    justify-content: center;",
            "    padding: 1.5rem;",
            "    z-index: 50;",
            "}",
            "",
            ".scan-popup {",
            "    position: relative;",
            "    width: min(1100px, 96vw);",
            "    max-height: 92vh;",
            "    height: min(900px, 92vh);",
            "    background: #0b0f1a;",
            "    border-radius: 1.5rem;",
            "    padding: 1.5rem;",
            "    box-sizing: border-box;",
            "    display: flex;",
            "    flex-direction: column;",
            "    align-items: stretch;",
            "    gap: 1.5rem;",
            "    overflow: hidden;",
            "    box-shadow: 0 30px 60px -25px rgba(0, 0, 0, 0.6);",
            "}",
            "",
            ".scan-popup.scan-camera-popup {",
            "    background: transparent;",
            "    border-radius: 1rem;",
            "    padding: 1rem;",
            "    box-shadow: none;",
            "}",
            "",
            ".scan-topbar {",
            "    position: relative;",
            "    width: 100%;",
            "    padding: 1rem 1.5rem;",
            "    display: flex;",
            "    align-items: center;",
            "    justify-content: space-between;",
            "    z-index: 10;",
            "}",
            "",
            ".scan-popup-footer {",
            "    display: flex;",
            "    justify-content: flex-end;",
            "    margin-top: 0.5rem;",
            "}",
            "",
            ".scan-close {",
            "    color: #ffffff;",
            "    padding: 0.5rem;",
            "}",
            "",
            ".scan-embedded .scan-close {",
            "    display: none;",
            "}",
            "",
            "html.scan-embedded,",
            "body.scan-embedded {",
            "    background: transparent;",
            "    height: 100%;",
            "    min-height: 0;",
            "    overflow: hidden;",
            "}",
            "",
            ".scan-embedded .scan-overlay {",
            "    position: static;",
            "    inset: auto;",
            "    padding: 0;",
            "    background: transparent;",
            "    min-height: 100%;",
            "}",
            "",
            ".scan-embedded .scan-popup {",
            "    width: 100%;",
            "    max-height: none;",
            "    height: 100%;",
            "    border-radius: 0;",
            "    padding: 1rem 1.5rem 1.5rem;",
            "    box-shadow: none;",
            "}",
            "",
            ".scan-embedded .scan-topbar {",
            "    display: none;",
            "}",
            "",
            ".scan-layout {",
            "    display: grid;",
            "    grid-template-columns: minmax(260px, 1fr) minmax(320px, 0.9fr);",
            "    gap: 1.5rem;",
            "    width: 100%;",
            "    align-items: start;",
            "}",
            "",
            ".scan-layout.single {",
            "    grid-template-columns: 1fr;",
            "}",
            "",
            ".scan-layout.single > div {",
            "    width: 100%;",
            "    display: flex;",
            "    flex-direction: column;",
            "    align-items: center;",
            "    gap: 1rem;",
            "}",
            "",
            ".scan-layout.single .scan-frame {",
            "    margin: 0 auto;",
            "}",
            "",
            ".scan-layout.single .scan-actions {",
            "    width: 100%;",
            "    justify-content: center;",
            "}",
            "",
            ".scan-frame {",
            "    width: 100%;",
            "    max-width: 24rem;",
            "    aspect-ratio: 3 / 4;",
            "    background: #1f2937;",
            "    border-radius: 1rem;",
            "    overflow: hidden;",
            "    border: 1px solid #334155;",
            "    box-shadow: 0 30px 60px -25px rgba(0, 0, 0, 0.6);",
            "    position: relative;",
            "    display: flex;",
            "    align-items: center;",
            "    justify-content: center;",
            "    padding: 0.35rem;",
            "}",
            "",
            ".scan-video-wrap {",
            "    position: relative;",
            "    width: 100%;",
            "    height: 100%;",
            "    background: #111827;",
            "    border-radius: 0.75rem;",
            "    overflow: hidden;",
            "}",
            "",
            ".scan-video-wrap video {",
            "    width: 100%;",
            "    height: 100%;",
            "    object-fit: cover;",
            "    opacity: 1;",
            "}",
            "",
            ".scan-state-overlay {",
            "    position: absolute;",
            "    inset: 0.35rem;",
            "    display: flex;",
            "    align-items: center;",
            "    justify-content: center;",
            "    pointer-events: none;",
            "}",
            "",
            ".scan-data-overlay {",
            "    position: absolute;",
            "    inset: 0.35rem;",
            "    display: flex;",
            "    align-items: stretch;",
            "    justify-content: flex-end;",
            "    padding: 1rem;",
            "    pointer-events: none;",
            "}",
            "",
            ".scan-data-feed {",
            "    width: 100%;",
            "    display: flex;",
            "    flex-direction: column;",
            "    gap: 0.4rem;",
            "    align-items: stretch;",
            "}",
            "",
            ".scan-data-item {",
            "    background: rgba(15, 23, 42, 0.35);",
            "    border: 1px solid rgba(148, 163, 184, 0.35);",
            "    color: #e2e8f0;",
            "    padding: 0.6rem 0.9rem;",
            "    border-radius: 0.85rem;",
            "    font-size: 0.75rem;",
            "    font-weight: 600;",
            "    letter-spacing: 0.02em;",
            "    backdrop-filter: blur(8px);",
            "    box-shadow: 0 18px 40px -25px rgba(15, 23, 42, 0.7);",
            "    opacity: 0;",
            "    transform: translateY(8px);",
            "    transition: opacity 0.25s ease, transform 0.25s ease;",
            "    text-align: left;",
            "}",
            "",
            ".scan-data-item.show {",
            "    opacity: 1;",
            "    transform: translateY(0);",
            "}",
            "",
            ".scan-data-item.fade {",
            "    opacity: 0;",
            "    transform: translateY(8px);",
            "}",
            "",
            ".scan-data-item.is-verifying {",
            "    background: rgba(15, 23, 42, 0.25);",
            "    border-color: rgba(148, 163, 184, 0.4);",
            "    color: #e2e8f0;",
            "    animation: scanVerifyPulse 1.6s ease-in-out infinite;",
            "}",
            "",
            ".scan-data-item.is-error {",
            "    border-color: rgba(239, 68, 68, 0.65);",
            "    background: rgba(239, 68, 68, 0.15);",
            "    color: #fecaca;",
            "}",
            "",
            ".scan-data-line + .scan-data-line {",
            "    margin-top: 0.2rem;",
            "}",
            "",
            ".scan-state-badge {",
            "    padding: 0.35rem 0.85rem;",
            "    border-radius: 999px;",
            "    font-size: 0.65rem;",
            "    font-weight: 700;",
            "    letter-spacing: 0.08em;",
            "    text-transform: uppercase;",
            "    background: rgba(15, 23, 42, 0.7);",
            "    color: #e2e8f0;",
            "    border: 1px solid rgba(148, 163, 184, 0.45);",
            "    backdrop-filter: blur(6px);",
            "    transition: transform 0.2s ease, background 0.2s ease, color 0.2s ease, border-color 0.2s ease;",
            "}",
            "",
            ".scan-state-pulse {",
            "    position: absolute;",
            "    width: 72%;",
            "    height: 72%;",
            "    border-radius: 999px;",
            "    border: 2px solid transparent;",
            "    opacity: 0;",
            "    display: none;",
            "}",
            "",
            ".scan-state-overlay::before {",
            "    content: \"\";",
            "    position: absolute;",
            "    top: 0;",
            "    left: 0;",
            "    right: 0;",
            "    height: 3px;",
            "    border-radius: 0.35rem;",
            "    background: linear-gradient(90deg, rgba(248, 113, 113, 0.1), rgba(248, 113, 113, 0.9), rgba(248, 113, 113, 0.1));",
            "    box-shadow: 0 0 12px rgba(248, 113, 113, 0.6);",
            "    opacity: 0;",
            "    animation: scanBarcode 1.6s ease-in-out infinite alternate;",
            "    animation-play-state: paused;",
            "}",
            "",
            ".scan-frame.is-searching {",
            "    border-color: #475569;",
            "}",
            "",
            ".scan-frame.is-searching .scan-state-overlay::before {",
            "    opacity: 1;",
            "    animation-play-state: running;",
            "}",
            "",
            ".scan-frame.is-searching .scan-state-badge {",
            "    background: rgba(15, 23, 42, 0.7);",
            "    color: #e2e8f0;",
            "    border-color: rgba(148, 163, 184, 0.45);",
            "}",
            "",
            ".scan-frame.is-analyzing {",
            "    border-color: #38bdf8;",
            "    box-shadow: 0 24px 40px -28px rgba(56, 189, 248, 0.6);",
            "}",
            "",
            ".scan-frame.is-analyzing .scan-state-badge {",
            "    background: rgba(14, 116, 144, 0.35);",
            "    color: #e0f2fe;",
            "    border-color: rgba(56, 189, 248, 0.6);",
            "}",
            "",
            ".scan-frame.is-found {",
            "    border-color: #22c55e;",
            "    box-shadow: 0 28px 50px -28px rgba(34, 197, 94, 0.6);",
            "}",
            "",
            ".scan-frame.is-found .scan-state-overlay::before {",
            "    opacity: 1;",
            "    animation-play-state: paused;",
            "}",
            "",
            ".scan-frame.is-found .scan-state-badge {",
            "    background: rgba(20, 83, 45, 0.6);",
            "    color: #dcfce7;",
            "    border-color: rgba(34, 197, 94, 0.7);",
            "    transform: scale(1.05);",
            "}",
            "",
            ".scan-frame.is-scanned {",
            "    border-color: #f59e0b;",
            "    box-shadow: 0 24px 44px -28px rgba(245, 158, 11, 0.55);",
            "}",
            "",
            ".scan-frame.is-scanned .scan-state-overlay::before {",
            "    opacity: 1;",
            "    animation-play-state: paused;",
            "}",
            "",
            ".scan-frame.is-scanned .scan-state-badge {",
            "    background: rgba(120, 53, 15, 0.55);",
            "    color: #fef3c7;",
            "    border-color: rgba(245, 158, 11, 0.75);",
            "    transform: scale(1.03);",
            "}",
            "",
            ".scan-frame.is-error {",
            "    border-color: #ef4444;",
            "}",
            "",
            ".scan-frame.is-error .scan-state-badge {",
            "    background: rgba(127, 29, 29, 0.6);",
            "    color: #fee2e2;",
            "    border-color: rgba(248, 113, 113, 0.65);",
            "}",
            "",
            "@keyframes scanVerifyPulse {",
            "    0%,",
            "    100% {",
            "        opacity: 0.6;",
            "    }",
            "    50% {",
            "        opacity: 1;",
            "    }",
            "}",
            "",
            "@keyframes scanBarcode {",
            "    0% {",
            "        top: 0;",
            "        opacity: 0.35;",
            "    }",
            "    50% {",
            "        opacity: 0.75;",
            "    }",
            "    100% {",
            "        top: calc(100% - 3px);",
            "        opacity: 0.35;",
            "    }",
            "}",
            "",
            ".scan-panel {",
            "    width: 100%;",
            "    max-width: 28rem;",
            "}",
            "",
            "@media (max-width: 860px) {",
            "    .scan-popup {",
            "        width: 100%;",
            "        max-height: none;",
            "        height: 100%;",
            "        border-radius: 0.75rem;",
            "        padding-top: 3.5rem;",
            "        overflow: hidden;",
            "    }",
            "",
            "    .scan-layout {",
            "        grid-template-columns: 1fr;",
            "    }",
            "}",
            "",
            ".scan-panel-card {",
            "    background: #ffffff;",
            "    border-radius: 1.25rem;",
            "    padding: 1.5rem;",
            "    box-shadow: 0 15px 30px -20px rgba(15, 23, 42, 0.35);",
            "    border: 1px solid var(--slate-100);",
            "}",
            "",
            ".scan-status {",
            "    margin: 0.75rem 0 1rem;",
            "    font-size: 0.75rem;",
            "}",
            "",
            ".scan-panel-header {",
            "    display: flex;",
            "    align-items: center;",
            "    justify-content: space-between;",
            "    gap: 1rem;",
            "    margin-bottom: 1rem;",
            "}",
            "",
            ".scan-panel-actions {",
            "    display: flex;",
            "    gap: 0.5rem;",
            "    flex-wrap: wrap;",
            "    justify-content: flex-end;",
            "}",
            "",
            ".scan-detail-grid {",
            "    display: grid;",
            "    grid-template-columns: repeat(2, 1fr);",
            "    gap: 0.75rem;",
            "}",
            "",
            ".scan-field-span { grid-column: span 2; }",
            "",
            ".scan-field {",
            "    background: var(--slate-50);",
            "    border: 1px solid var(--slate-200);",
            "    border-radius: 0.75rem;",
            "    padding: 0.65rem;",
            "    font-size: 0.85rem;",
            "    color: var(--slate-700);",
            "}",
            "",
            ".scan-label-preview {",
            "    padding: 0;",
            "    overflow: hidden;",
            "}",
            "",
            ".scan-label-frame {",
            "    width: 100%;",
            "    height: 260px;",
            "    border: none;",
            "    display: block;",
            "    background: #ffffff;",
            "}",
            "",
            ".scan-label-link {",
            "    margin-top: 0.5rem;",
            "    display: inline-flex;",
            "}",
            "",
            ".scan-actions {",
            "    display: flex;",
            "    gap: 0.75rem;",
            "    margin-top: 1.25rem;",
            "}",
            "",
            ".scan-camera-actions {",
            "    width: 100%;",
            "    justify-content: center;",
            "}",
            "",
            ".scan-toggle {",
            "    padding: 0.65rem 1.4rem;",
            "    border-radius: 999px;",
            "    border: 1px solid #334155;",
            "    background: #0f172a;",
            "    color: #e2e8f0;",
            "    font-size: 0.8rem;",
            "    font-weight: 700;",
            "    text-transform: uppercase;",
            "    letter-spacing: 0.08em;",
            "    cursor: pointer;",
            "    transition: background 0.2s ease, color 0.2s ease, border-color 0.2s ease;",
            "}",
            "",
            ".scan-toggle:hover {",
            "    background: #1f2937;",
            "    border-color: #475569;",
            "    color: #ffffff;",
            "}"
    );

    public static final String SCAN_OVERLAY = "scan-overlay";
    public static final String SCAN_POPUP = "scan-popup";
    public static final String SCAN_POPUP_CAMERA = "scan-popup scan-camera-popup fade-in";
    public static final String SCAN_TOPBAR = "scan-topbar";
    public static final String SCAN_POPUP_FOOTER = "scan-popup-footer";
    public static final String SCAN_CLOSE = "scan-close";
    public static final String SCAN_LAYOUT = "scan-layout";
    public static final String SCAN_LAYOUT_SINGLE = "scan-layout single";
    public static final String SCAN_FRAME = "scan-frame";
    public static final String SCAN_VIDEO_WRAP = "scan-video-wrap";
    public static final String SCAN_STATE_OVERLAY = "scan-state-overlay";
    public static final String SCAN_STATE_BADGE = "scan-state-badge";
    public static final String SCAN_DATA_OVERLAY = "scan-data-overlay";
    public static final String SCAN_DATA_FEED = "scan-data-feed";
    public static final String SCAN_PANEL = "scan-panel";
    public static final String SCAN_PANEL_CARD = "scan-panel-card";
    public static final String SCAN_PANEL_HEADER = "scan-panel-header";
    public static final String SCAN_PANEL_ACTIONS = "scan-panel-actions";
    public static final String SCAN_DETAIL_GRID = "scan-detail-grid";
    public static final String SCAN_FIELD = "scan-field";
    public static final String SCAN_FIELD_SPAN = "scan-field-span";
    public static final String SCAN_ACTIONS = "scan-actions";
    public static final String SCAN_CAMERA_ACTIONS = "scan-actions scan-camera-actions";
    public static final String SCAN_TOGGLE = "scan-toggle";

    private CameraPopupCss() {
        throw new IllegalStateException("Utility class");
    }

    public static String join(String... classes) {
        if (classes == null || classes.length == 0) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (String cls : classes) {
            if (cls == null) {
                continue;
            }
            String trimmed = cls.trim();
            if (trimmed.isEmpty()) {
                continue;
            }
            if (!sb.isEmpty()) {
                sb.append(' ');
            }
            sb.append(trimmed);
        }
        return sb.toString();
    }
}


